// ─────────────────────────────────────────────────────────────────────────────
// interactions/coupleInteractions.ts  —  All 15 couple interaction definitions
// ─────────────────────────────────────────────────────────────────────────────
import type { Interaction } from '../character/types';

export const INTERACTIONS: Interaction[] = [
  {
    id: 'wave',
    label: 'Wave',
    emoji: '👋',
    requiresPartner: false,
    bondLevelRequired: 0,
    duration: 2000,
    partnerMustAccept: false,
    animState: 'wave',
    partnerAnimState: 'idle',
    particleEffect: null,
    bondXPReward: 1,
  },
  {
    id: 'hug',
    label: 'Hug',
    emoji: '🤗',
    requiresPartner: true,
    bondLevelRequired: 1,
    duration: 3000,
    partnerMustAccept: true,
    animState: 'hug',
    partnerAnimState: 'hug',
    particleEffect: 'hearts',
    bondXPReward: 8,
  },
  {
    id: 'sidehug',
    label: 'Side Hug',
    emoji: '🫂',
    requiresPartner: true,
    bondLevelRequired: 1,
    duration: 3000,
    partnerMustAccept: false,
    animState: 'sidehug',
    partnerAnimState: 'sidehug',
    particleEffect: 'hearts',
    bondXPReward: 7,
  },
  {
    id: 'highfive',
    label: 'High Five',
    emoji: '✋',
    requiresPartner: true,
    bondLevelRequired: 1,
    duration: 1500,
    partnerMustAccept: false,
    animState: 'highfive',
    partnerAnimState: 'highfive',
    particleEffect: 'sparkle',
    bondXPReward: 5,
  },
  {
    id: 'clap',
    label: 'Clap',
    emoji: '👏',
    requiresPartner: true,
    bondLevelRequired: 1,
    duration: 3000,
    partnerMustAccept: false,
    animState: 'clap',
    partnerAnimState: 'clap',
    particleEffect: 'notes',
    bondXPReward: 4,
  },
  {
    id: 'cheer',
    label: 'Cheer',
    emoji: '🙌',
    requiresPartner: true,
    bondLevelRequired: 1,
    duration: 2500,
    partnerMustAccept: false,
    animState: 'cheer',
    partnerAnimState: 'cheer',
    particleEffect: 'confetti',
    bondXPReward: 5,
  },
  {
    id: 'dance',
    label: 'Dance',
    emoji: '💃',
    requiresPartner: true,
    bondLevelRequired: 2,
    duration: 'hold',
    partnerMustAccept: true,
    animState: 'dance',
    partnerAnimState: 'dance',
    particleEffect: 'petals',
    bondXPReward: 12,
  },
  {
    id: 'spin',
    label: 'Spin Together',
    emoji: '🌀',
    requiresPartner: true,
    bondLevelRequired: 2,
    duration: 3000,
    partnerMustAccept: false,
    animState: 'spin',
    partnerAnimState: 'spin',
    particleEffect: 'petals',
    bondXPReward: 10,
  },
  {
    id: 'piggyback',
    label: 'Piggyback',
    emoji: '🫶',
    requiresPartner: true,
    bondLevelRequired: 2,
    duration: 'hold',
    partnerMustAccept: true,
    animState: 'walk',
    partnerAnimState: 'piggyback_rider',
    particleEffect: null,
    bondXPReward: 0,
  },
  {
    id: 'headpat',
    label: 'Head Pat',
    emoji: '🥰',
    requiresPartner: true,
    bondLevelRequired: 3,
    duration: 2500,
    partnerMustAccept: false,
    animState: 'headpat',
    partnerAnimState: 'idle',
    particleEffect: 'stars',
    bondXPReward: 6,
  },
  {
    id: 'sit_together',
    label: 'Sit Together',
    emoji: '🪑',
    requiresPartner: true,
    bondLevelRequired: 1,
    duration: 'hold',
    partnerMustAccept: false,
    animState: 'sit',
    partnerAnimState: 'sit',
    particleEffect: null,
    bondXPReward: 3,
  },
  {
    id: 'point',
    label: 'Point',
    emoji: '👉',
    requiresPartner: false,
    bondLevelRequired: 0,
    duration: 2000,
    partnerMustAccept: false,
    animState: 'point',
    partnerAnimState: 'idle',
    particleEffect: null,
    bondXPReward: 0,
  },
  {
    id: 'forehead_kiss',
    label: 'Forehead Kiss',
    emoji: '😘',
    requiresPartner: true,
    bondLevelRequired: 4,
    duration: 2500,
    partnerMustAccept: false,
    animState: 'lean_forward',
    partnerAnimState: 'tilt_down',
    particleEffect: 'sparkle',
    bondXPReward: 15,
  },
  {
    id: 'carry',
    label: 'Carry',
    emoji: '💪',
    requiresPartner: true,
    bondLevelRequired: 3,
    duration: 'hold',
    partnerMustAccept: true,
    animState: 'carry_carrier',
    partnerAnimState: 'carry_rider',
    particleEffect: null,
    bondXPReward: 0,
  },
  {
    id: 'kiss',
    label: 'Kiss',
    emoji: '💋',
    requiresPartner: true,
    bondLevelRequired: 5,
    duration: 2000,
    partnerMustAccept: true,
    animState: 'lean_forward',
    partnerAnimState: 'lean_forward',
    particleEffect: 'heart_burst',
    bondXPReward: 20,
  },
];

export const INTERACTION_MAP = Object.fromEntries(
  INTERACTIONS.map((i) => [i.id, i])
) as Record<string, Interaction>;
